### ISSUE TITLE
Can't display map (CORS Issue)

### ISSUE THREAD

**Issue by ImaCrea** [plain-solutions-gmbh/kirby-map#16]
Hello there,
thanks for this great plugin.

On the panel, everything looks fine. But on the front side, block seems to be loaded by kirby but nothing shows.

I get this error in the console on Firefox :
<img width="574" alt="Capture d’écran 2024-10-23 à 17 36 24" src="https://github.com/user-attachments/assets/1d405e8c-1386-4c5d-a55e-24874b47cd83">

Same on Safari:
<img width="565" alt="Capture d’écran 2024-10-23 à 17 36 55" src="https://github.com/user-attachments/assets/2c304050-6c71-4f87-892e-cbcf06b46677">

No extension, or adblocker activated on browser. 

I wonder if I'm the only one with this 🤷 

Here's setting for api key:
 
![Capture d’écran 2024-10-23 à 17 33 43](https://github.com/user-attachments/assets/43df8a19-8c1f-4092-b681-bd00e92ab79c)

What puzzles me is that the map shows correctly in the panel.

<img width="585" alt="Capture d’écran 2024-10-23 à 17 38 53" src="https://github.com/user-attachments/assets/5615d7b4-a305-4561-946c-3502b664102f">

Same issue wether I'm on local dev or remote prod.

Thanks for your help!

**Comment by plain-solutions-gmbh** [comment]
It's hard to reproduce. Is there an example page where i can see this..?

**Comment by ImaCrea** [comment]
Thanks for your help. I see what a CORS error is but I wonder how you do to mitigate it ? Also, why it's happening on the front but not on the CMS side puzzles me.

**Comment by plain-solutions-gmbh** [comment]
I know CORS is not easy to understand easely. But it is a important feature for security. (Inject mal javascript)
Maybe you'il find a solution [here](https://forum.getkirby.com/t/easy-way-to-enable-cors/3013).

**Comment by ImaCrea** [comment]
It appears the error is not related to CORS but to the browser blocking mapbox as being seen as a tracker. I'll try something else. Thanks for your time and generosity.
